SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI, REST_REVIEW RR
WHERE RI.REST_ID = RR.REST_ID and RI.ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, RI.FAVORITES DESC
